/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface CloudflareEnv cloudflare-env.d.ts` (hash: 00cdbd91dd4ebe39ca9ac827d1d89552)
//
// Manual addition: pulls runtime types from @cloudflare/workers-types so
// D1Database/Fetcher/etc. resolve. Without --include-runtime, wrangler types
// stops emitting them inline; this directive backfills the source.
/// <reference types="@cloudflare/workers-types" />

declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/_worker.js/index");
		durableNamespaces: "DocumentWebSocket";
	}
	interface Env {
		DB: D1Database;
		ASSETS: Fetcher;
		CLOUDFLARE_API_TOKEN: string;
		DOCUMENT_WS: DurableObjectNamespace<import("./dist/_worker.js/index").DocumentWebSocket>;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLOUDFLARE_API_TOKEN">> {}
}
